apiVersion: core.spinoperator.dev/v1
kind: SpinApp
metadata:
  name: keda-spinapp
spec:
  # TODO: Depend on a ghcr.io version of this image
  image: "ttl.sh/cpu-load-gen:1h"
  executor: containerd-shim-spin
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 400Mi
